/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


*/


class Solution {
public:
    char findTheDifference(string s, string t) {
        char res = 0;
        for(char i: s)
            res ^= i;
        for(char i: t)
            res ^= i;
        return res;
    }
};


class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> map;
        for(auto c : s){
            map[c]++;
        }
        for(auto c : t){
            if(map.find(c)==map.end() || map[c]==0) return c;
            map[c]--;
        }
        return ' ';
    }
};