"""
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        miss = 0
        for i, j in zip(s,t):
            miss = miss ^ ord(i) ^ ord(j)
        return chr(miss^ord(t[-1]))

import functools
class Solution:
    def findTheDifference(self, s, t):
        return chr(functools.reduce(operator.xor, map(ord, s+t)))

import functools
class Solution:
    def findTheDifference(self, s, t):
        res = lambda w: functools.reduce(lambda x, y: x^ord(y), w, 0) #需要初始化为0, 否则会认为初始化是string “”
        return chr(res(s+t))

class Solution:
    def findTheDifference(self, s, t):

        c1 = collections.Counter(s);
        c2 = collections.Counter(t);
        for item in (c2 - c1):
            return item
        return None
